[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3 